go_login_menu_text = '⚙️ Управление GoLogin аккаунтами'
create_go_login_text = 'Выберите способ создания GoLogin аккаунта:'
token_create_go_login_text = 'Введите токен профиля:'
create_go_login_success_text = '✅ Аккаунт GoLogin успешно добавлен.\n'
create_go_login_error_text = '❌ Ошибка при добавлении аккаунта GoLogin.\n'
delete_go_login_text = '🗑 Аккаунт удалён.'
go_login_account_text = lambda account: (f'Аккаунт: {account.id}\n'
                                         f'Почта: {account.email_address}\n'
                                         f'Дата создания: {account.registration_date.strftime("%d.%m.%Y")}\n\n'
                                         f'Токен: {account.api_token}\n'
                                         f'Выберите действие:')
wait_create_go_login_text = 'Создание профиля...'